export async function GET(request: Request, { params }: { params: { filename: string } }) {
  try {
    const { filename } = params

    // In a real implementation, you would call your FastAPI backend here
    // const response = await fetch(`http://your-backend:8000/download/${filename}`)

    // For demo purposes, return a sample file
    const sampleContent = `# Sample Analysis Results

This is a sample file generated by the AI Text Analysis Suite.

## Processing Results
- Entities extracted: 25
- Coreferences resolved: 18
- Contradictions found: 2

Generated on: ${new Date().toISOString()}
`

    return new Response(sampleContent, {
      headers: {
        "Content-Type": "text/markdown",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    })
  } catch (error) {
    return Response.json({ error: "File not found" }, { status: 404 })
  }
}
